# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-pagin}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yung Hwa Kwon"]
  s.date = %q{2010-02-15}
  s.description = %q{Small utility to process paginated urls without modifying the mapped paths in your Sinatra app}
  s.email = %q{yung.kwon@nowk.net}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "Changelog.md",
     "Gemfile",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/sinatra/pagin.rb",
     "sinatra-pagin.gemspec",
     "spec/pagin_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nowk/sinatra-pagin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Small utility to process paginated urls without modifying the mapped paths in your Sinatra app}
  s.test_files = [
    "spec/pagin_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_development_dependency(%q<webrat>, [">= 0.7.0"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.2"])
    else
      s.add_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_dependency(%q<rspec>, [">= 1.2.8"])
      s.add_dependency(%q<webrat>, [">= 0.7.0"])
      s.add_dependency(%q<rack-test>, [">= 0.5.2"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0.9.4"])
    s.add_dependency(%q<rspec>, [">= 1.2.8"])
    s.add_dependency(%q<webrat>, [">= 0.7.0"])
    s.add_dependency(%q<rack-test>, [">= 0.5.2"])
  end
end

